server:
  port: 4000

minio:
  url: http://123.60.83.190:9000
  accessKey: minioadmin
  secretKey: minioadmin


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 500MB