server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://js-club-oss-dev
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://js-club-subject-dev
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1